# Generated by Django 3.2.18 on 2023-03-16 16:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customeraddress_customerdictsettings_customerpaymentmethod'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of last update'),
        ),
        migrations.AddField(
            model_name='customerdictsettings',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerdictsettings',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of last update'),
        ),
        migrations.AddField(
            model_name='customerpaymentmethod',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Date of creation'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='customerpaymentmethod',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Date of last update'),
        ),
    ]
