# Generated by Django 3.2.18 on 2023-03-18 12:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_auto_20230316_1601'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdictsettings',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name="Customer's settings"),
        ),
    ]
