# Generated by Django 3.2.18 on 2023-03-14 15:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_alter_customuser_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerDictSettings',
            fields=[
                ('email_address', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name="Customer's email address")),
                ('first_name', models.CharField(max_length=20, verbose_name="Customer's name")),
                ('last_name', models.CharField(max_length=30, verbose_name="Customer's last name")),
                ('mobile_number', models.CharField(max_length=30, verbose_name="Customer's mobile number")),
                ('isAgreeSendMessagesOnEmail', models.BooleanField(default=False, verbose_name='Does customer agree on mailing list')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to=settings.AUTH_USER_MODEL, verbose_name="Customer's settings")),
            ],
        ),
        migrations.CreateModel(
            name='CustomerPaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=16, verbose_name="Customer's payment method card number")),
                ('expire_date', models.DateField()),
                ('customer_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cards', to='customers.customerdictsettings', verbose_name="Customer's payment cards")),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=30, verbose_name='Country where customer lives')),
                ('city', models.CharField(max_length=20, verbose_name='City where customer lives')),
                ('street', models.CharField(max_length=20, verbose_name='Street where customer lives')),
                ('house_number', models.CharField(max_length=10, verbose_name="House number customer's address")),
                ('flat_number', models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name="Flat number customer's address")),
                ('postal_code', models.CharField(max_length=20, verbose_name="Customer's postal code")),
                ('customer_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='customers.customerdictsettings', verbose_name="Customer's addresses")),
            ],
        ),
    ]
