# Generated by Django 3.2.18 on 2023-03-23 14:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customerdictsettings_customer'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerPaymentCardMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of last update')),
                ('is_active', models.BooleanField(default=False, verbose_name="Is active object from list of Customer's settings")),
                ('card_number', models.CharField(max_length=16, verbose_name="Customer's payment method card number")),
                ('expire_date', models.DateTimeField()),
                ('customer_settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payment_cards', to='customers.customerdictsettings', verbose_name="Customer's payment cards")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name="Is active object from list of Customer's settings"),
        ),
        migrations.DeleteModel(
            name='CustomerPaymentMethod',
        ),
    ]
