# Generated by Django 3.2.18 on 2023-04-20 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0005_auto_20230323_1438'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='street',
            field=models.CharField(max_length=50, verbose_name='Street where customer lives'),
        ),
    ]
