# Generated by Django 3.2.18 on 2023-04-20 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0007_auto_20230420_1316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerdictsettings',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Customer's last name"),
        ),
    ]
