# Generated by Django 3.2.18 on 2023-04-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0008_alter_customerdictsettings_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeraddress',
            name='city',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='City where customer lives'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='country',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='Country where customer lives'),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='flat_number',
            field=models.PositiveIntegerField(blank=True, default=None, null=True, verbose_name="Flat number customer's address"),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='house_number',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name="House number customer's address"),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='postal_code',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Customer's postal code"),
        ),
        migrations.AlterField(
            model_name='customeraddress',
            name='street',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Street where customer lives'),
        ),
        migrations.AlterField(
            model_name='customerdictsettings',
            name='email_address',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name="Customer's email address"),
        ),
        migrations.AlterField(
            model_name='customerdictsettings',
            name='first_name',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name="Customer's name"),
        ),
        migrations.AlterField(
            model_name='customerdictsettings',
            name='mobile_number',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name="Customer's mobile number"),
        ),
        migrations.AlterField(
            model_name='customerpaymentcardmethod',
            name='card_number',
            field=models.CharField(blank=True, max_length=16, null=True, verbose_name="Customer's payment method card number"),
        ),
        migrations.AlterField(
            model_name='customerpaymentcardmethod',
            name='expire_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
