# Generated by Django 3.2.18 on 2023-04-29 09:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0009_auto_20230420_1401'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerStatisticModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Date of last update')),
                ('success', models.BooleanField(default=False, verbose_name='Did extension fill successfully')),
                ('price', models.DecimalField(decimal_places=2, default=None, max_digits=6, null=True, verbose_name="Order's price")),
                ('site', models.CharField(default=None, max_length=64, null=True, verbose_name='Site')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='customers.customerdictsettings', verbose_name="Customer's statistic")),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FillField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name="Field's name")),
                ('is_filled', models.BooleanField(default=False, verbose_name='Was field filled')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Date of creation')),
                ('statistic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='customers.customerstatisticmodel', verbose_name='Filled fields')),
            ],
        ),
    ]
