# Generated by Django 3.2.18 on 2023-04-29 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0011_alter_customerstatisticmodel_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerstatisticmodel',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statistic', to='customers.customerdictsettings', verbose_name="Customer's statistic"),
        ),
    ]
