# Generated by Django 3.2.18 on 2023-04-29 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0012_alter_customerstatisticmodel_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customerstatisticmodel',
            old_name='customer',
            new_name='settings',
        ),
    ]
